export const experiencia = [
  {
    image: 'SGS.png',
    alt: 'Imagen Corporativa SGS',
    cargo: 'Profesional Semi Senior',
    fecha: 'Diciembre 2023 - Actual',
    lugar: 'Santa Fe de Bogotá DC',
    actividades: [
      'Certificar la calidad y cantidad de los hidrocarburos y refinados.',
      'Realizar seguimiento a los Carrotanques recibidos y despachados.',
      'Elaborar los reportes diarios y mensuales.',
      'Implementar y mantener la Norma ISO 17025 – 2017.',
      'Desarrollé el programa Balance para calcular los balances diarios y mensuales.',
      'Desarrollé el programa LabCal para realizar los cálculos de los análisis.',
    ],
    jefe: 'Hernando Rosales - Telefono 314 23852 39',
  },
  {
    image: 'SGS.png',
    alt: 'Imagen Corporativa Soluciones Inmediatas',
    cargo: 'Programador Integrador',
    fecha: 'Agosto 2023 - Noviembre 2023',
    lugar: 'Santa Fe de Bogotá DC',
    actividades: [
      'Certificar la calidad y cantidad de los hidrocarburos y refinados.',
      'Realizar seguimiento a los Carrotanques recibidos y despachados.',
      'Elaborar los reportes diarios y mensuales.',
      'Implementar y mantener la Norma ISO 17025 – 2017.',
      'Desarrollé el programa Balance para calcular los balances diarios y mensuales.',
      'Desarrollé el programa LabCal para realizar los cálculos de los análisis.',
    ],
    jefe: 'Hernando Rosales - Telefono 314 23852 39',
  },
  {
    image: 'SGS.png',
    alt: 'Imagen Corporativa SGS',
    cargo: 'Inspector Profesional',
    fecha: 'Julio 2021 - Actual',
    lugar: 'Apiay Cenit Villavicencio - Meta',
    actividades: [
      'Certificar la calidad y cantidad de los hidrocarburos y refinados.',
      'Realizar seguimiento a los Carrotanques recibidos y despachados.',
      'Elaborar los reportes diarios y mensuales.',
      'Implementar y mantener la Norma ISO 17025 – 2017.',
      'Desarrollé el programa Balance para calcular los balances diarios y mensuales.',
      'Desarrollé el programa LabCal para realizar los cálculos de los análisis.',
    ],
    jefe: 'Hernando Rosales - Telefono 314 23852 39',
  },
  {
    image: 'Intertek.png',
    alt: 'Imagen Corporativa Intertek',
    cargo: 'Coordinador Administrativo de Contratos',
    fecha: 'Junio 2019 – Junio 2021 ',
    lugar: 'Santa Fe de Bogotá DC',
    actividades: [
      'Coordinar 6 proyectos de inspección de Hidrocarburos.',
      'Liderar un equipo de 50 personas.',
      'Planear y ejecutar las auditorias de sistemas de transporte de Hidrocarburos.',
      'Gestionar el proceso de adquisición de bienes y servicios.',
      'Implemente estrategias para el desarrollo y seguimiento de indicadores corporativos y desempeño laboral.',
      'Desarrollé el programa Nomina para calcular los recargos y horas extras.',
    ],
    jefe: 'Cristhian Moreno – Teléfono: 314 238 52 39',
  },
  ,
  {
    image: 'OTI.jpg',
    alt: 'Imagen Corporativa OTI',
    cargo: 'Inspector de Hidrocarburos',
    fecha: 'Febrero 2017 – Junio 2019  ',
    lugar: 'Rubiales CPF1 y CPF2 -Puerto Gaitán – Meta',
    actividades: [
      'Certificar la calidad y cantidad de los hidrocarburos.',
      'Realizar seguimiento a Carrotanques.',
      'Elaborar los reportes diarios y mensuales.',
      'Implementar y mantener la Norma ISO 17025 – 2017',
      'Desarrollé el programa Analito para realizar los cálculos de los análisis y balances diarios y mensuales.',
    ],
    jefe: 'Jorge Santander – Teléfono: 316 223 09 55',
  },
  ,
  {
    image: 'BV.jpg',
    alt: 'Imagen Corporativa BV',
    cargo: 'Inspector de Calidad y Cantidad',
    fecha: 'Junio 2008 – Julio 2016',
    lugar: 'Ocensa Coveñas - Coveñas – Sucre',
    actividades: [
      'Certificar la calidad y cantidad de los hidrocarburos.',
      'Elaborar los reportes diarios y mensuales.',
      'Implementar y mantener la Norma ISO 17025 – 2017',
      'Realizar las inspecciones de volúmenes en Buque Tanques.',
    ],
    jefe: 'Cornelio Toledo – Teléfono: 300 404 81 669',
  },
]
