export const experiencia = [
  {
    image: 'SGS.png',
    alt: 'Imagen Corporativa SGS',
    cargo: 'Inspector Profesional',
    fecha: 'Julio 2021 - Actual',
    lugar: 'Apiay Cenit Villavicencio - Meta',
    actividades: [
      'Certificar la calidad y cantidad de los hidrocarburos y refinados.',
      'Realizar seguimiento a los Carrotanques recibidos y despachados.',
      'Elaborar los reportes diarios y mensuales.',
      'Implementar y mantener la Norma ISO 17025 – 2017.',
      'Desarrollé el programa Balance para calcular los balances diarios y mensuales.',
      'Desarrollé el programa LabCal para realizar los cálculos de los análisis.',
    ],
    jefe: 'Hernando Rosales - Telefono 314 23852 39',
  },
  {
    image: 'Intertek.png',
    alt: 'Imagen Corporativa Intertek',
    cargo: 'Coordinador Administrativo de Contratos',
    fecha: 'Junio 2019 – Junio 2021 ',
    lugar: ' Santa Fe de Bogotá',
    actividades: [
      'Encargado de Coordinar 6 proyectos de inspección de Hidrocarburos.',
      'Liderar un equipo de 50 personas.',
      'Planear y ejecutar las auditorias de sistemas de transporte de Hidrocarburos.',
      'Gestionar el proceso de adquisición de bienes y servicios.',
      'Implemente estrategias para el desarrollo y seguimiento de indicadores corporativos y desempeño laboral.',
      'Desarrollé el programa Nomina para calcular los recargos y horas extras.',
    ],
    jefe: 'Cristhian Moreno – Teléfono: 314 238 52 39',
  },
  ,
  {
    image: 'OTI.jpg',
    alt: 'Imagen Corporativa OTI',
    cargo: 'Inspector de Hidrocarburos',
    fecha: 'Febrero 2017 – Junio 2019  ',
    lugar: 'Rubiales CPF1 y CPF2 -Puerto Gaitán – Meta',
    actividades: [
      'Encargado de Coordinar 6 proyectos de inspección de Hidrocarburos.',
      'Liderar un equipo de 50 personas.',
      'Planear y ejecutar las auditorias de sistemas de transporte de Hidrocarburos.',
      'Gestionar el proceso de adquisición de bienes y servicios.',
      'Implemente estrategias para el desarrollo y seguimiento de indicadores corporativos y desempeño laboral.',
      'Desarrollé el programa Nomina para calcular los recargos y horas extras.',
    ],
    jefe: 'Cristhian Moreno – Teléfono: 314 238 52 39',
  },
  ,
  {
    image: 'Intertek.png',
    alt: 'Imagen Corporativa BV',
    cargo: 'Coordinador Administrativo de Contratos',
    fecha: 'Junio 2019 – Junio 2021 ',
    lugar: ' Santa Fe de Bogotá',
    actividades: [
      'Encargado de Coordinar 6 proyectos de inspección de Hidrocarburos.',
      'Liderar un equipo de 50 personas.',
      'Planear y ejecutar las auditorias de sistemas de transporte de Hidrocarburos.',
      'Gestionar el proceso de adquisición de bienes y servicios.',
      'Implemente estrategias para el desarrollo y seguimiento de indicadores corporativos y desempeño laboral.',
      'Desarrollé el programa Nomina para calcular los recargos y horas extras.',
    ],
    jefe: 'Cristhian Moreno – Teléfono: 314 238 52 39',
  },
]
